variables:
  CI_IMAGE: "gcr.io/pledra-1/product-configurator"
  CI_IMAGE_TAG: "12.0-${CI_COMMIT_SHA}"
  GCLOUD_PROJECT: "pledra-1"

include:
  - project: 'pledra/pledra-doodba-scaffolding'
    file: '/templates/.gitlab-ci-template.yml'

